#!/usr/bin/env bash
city=$1
country=$2

if [ -z "$city" ]; then
    echo "Please, type a city"
    exit 
fi

if [ -z "$country" ]; then
    country="br"
fi

curl -sS "http://api.openweathermap.org/data/2.5/weather?q=$city,$country&appid=23a9744017bf02ed2d7ae1de269d5e93&units=metric" | grep -Eoi "temp\":.+,\"pre" | cut -c "7-" | cut -d , -f 1
